export const ROLES = {
  ADMIN: 'ADMIN',
  COMPRAS: 'COMPRAS',
  AREA_SOLICITANTE: 'AREA_SOLICITANTE',
  EVALUADOR_TECNICO: 'EVALUADOR_TECNICO',
  EVALUADOR_ECONOMICO: 'EVALUADOR_ECONOMICO',
  APROBADOR: 'APROBADOR',
  AUDITOR: 'AUDITOR',
  PROVEEDOR: 'PROVEEDOR',
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];
